version: '3'
services:
  hugo:
    build: .
    ports:
      - "1313:1313"
    volumes:
      - .:/src
    environment:
      - HUGO_WATCH=true
      - HUGO_ENV=development
    command: ["hugo", "server", "--bind", "0.0.0.0", "--watch"] 
